config/routes.rb
Rails.application.routes.draw do
  get 'faqs/index'

  resources :orders do
    resources :items,on: :member
  end
  get 'orders/index'
  devise_for :users ,:path_names=>{sign_in: 'login',sign_out:'logout',sign_up:'register'},:controllers => {:registrations => "registrations"}
  

   root :to =>'orders#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
 belongs_to (:order)
 self.table_name='vwkarmorders'
 self.establish_connection(:karm)
def self.search(search)
 if search
   where('itemcode like ?',"%#{search}%")
 else
   all
 end
end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :items
 self.table_name='vwkarmpoainfo'
 self.establish_connection(:karm)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  self.table_name='portaluser'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper LaterDude::CalendarHelper
  protect_from_forgery with: :exception
   
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  # GET /items
  # GET /items.json
  def index
    begin
     @items=Item.search(params[:search]).order('itemcode').where("pono=? and email=?",params[:pono],current_user.email).paginate(page: params[:page],per_page: 10)
     respond_to do |format| 
       format.js()
       format.html()
       flash[:notice]= "P.O NUMBER #{params[:pono]}"
     end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url,:alert=>'Invalid request'
    end
  end
    private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:pono, :description, :itemcode,:order_id,:email,:search)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  # GET /orders
  # GET /orders.json
  def index
    begin
      @search=Order.search(params[:q])
      @orders=@search.result.order('orderdate').where('email=?' ,current_user.email).paginate(page: params[:page],per_page: 10)
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url,:alert=>'Invalid request'
    end
  end
  # GET /orders/1
  # GET /orders/1.json
private 
def order_params
      params.require(:order).permit(:pono,:order_id)
 end
end

app/controllers/registrations_controller.rb
class RegistrationsController <  Devise::RegistrationsController
  before_filter :authenticate_user!, :only => :token
  before_action :confirm_user,:only =>:create
  def new
      super
    end
  def create
    if (@user.count>0)
      super
    else
      redirect_to new_user_registration_path,:alert=>"provided mail is not registered with us"
    end
  end
  def update
    super
  end
private
  def confirm_user
    @user=User.connection.exec_query("SELECT Emailaddress FROM Customers_emailaddress WHERE Emailaddress='#{params[:user][:email]}'")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/faqs/index.html.erb
<%breadcrumb :faqs,faqs_index_path%>
<h1>Frequently asked questions</h1>
<div class="faqs">
  <dl>
    <dt>1.How do I register?</dt>
    <dd>
      To register provide a valid email 
      address and a password at least six
      characters long.
    </dd>
    <dt>2.Why cant I register even after providing a valid email?</dt>
    <dd>
       The email address you are using is not registered with us.
    </dd>
    <dt>3.After registration what next?</dt>
    <dd>
        An activation link will be sent to the provided email address.
        This link expires in 6 hours.
    </dd>
  </dl>
  <%if user_signed_in? %>
  <span class="badge" id="backbtn"><%=link_to "Back",:back,:id=>'backbtn'%></span>
  <%else%>
    <span class="badge" id="backbtn"><%=link_to "Register/login",new_user_session_path,:id=>'backbtn'%></span>
  <%-end-%>
  
</div>

app/views/items/_items.html.erb
<div class="searchinfo">
  <%=form_tag order_items_path,:class=>"navbar-form navbar-search",:role=> "search" ,:method=> 'get',:remote=> true do%>
  <div class="form-group">
    <%=text_field_tag :search,params[:search],:placeholder=>"Search for an item",:class=>"form-control input-large"%>
    <%=hidden_field_tag :pono,params[:pono]%>
    <%=submit_tag "Search",:class=>"btn btn-default",:method=>:get%>
  </div>
  <%-end-%>
</div>
 <table class="table table-striped" id="items">
  <thead>
    <tr>
      <th>ITEM CODE</th>
      <th>ORD QTTY</th>
      <th>DISPATCHED</th>
      <th>BALANCE</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
       <td><%= item.itemcode %></td>
         <td><%= item.quantity %></td>
         <td><%= item.dispatched %></td>
         <td><%= item.balance %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%if @items.count>10%>
  <div class="well well-small">
  <ul class="pager">
         <li class="btn-mini"><%=will_paginate @items,:container=>false%></li>
   </ul>
 </div>
<%-end-%>

app/views/items/index.html.erb
<% breadcrumb :orders,@orders%>
<% breadcrumb :orders, @items%>
<div class="page-header">
  <h1>Listing order items</h1>
</div>
  <%if alert%>
   <span class="label label-error">
      <a href="#"  data-dismiss="alert">&times;</a>
    <%=alert %>
     <%flash[:alert]=nil%>
  </span> 
    <%-end-%>
    <%if notice%>
    <span class="label label-info">
    <%=notice %>
     <%flash[:notice]=nil%>
    </span>
    <%-end-%>

<% if @items && @items.count>0 %>
 <div id="orderinfo"> <%= render :partial=> 'items'%> </div>
 <%else%>
           <div  class="alert-info">
               <a href="#"  data-dismiss="alert">&times;</a>
               <p> The POA has <%= @items.count%> items </p>
            </div>
<%-end-%>
<span class="badge" id="backbtn"><%=link_to "Back",:back,:id=>"backbtn",:notice=>nil%></span> 

app/views/items/index.js.erb
$('#orderinfo').html("<%= j( render "items") %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "| K.A.R.M Order Portal" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
 <body>
  <div id="main"> 
	
	<header>
	  <div id="welcome">
	    <h2>K.A.R.M <span>Order Portal</span></h2>
	  </div><!--close welcome-->			  	
	
	  <nav>
	    <div id="menubar">
          <ul id="nav">
            <li class="current"><%=link_to("Home",:root)%></li>  <li><%=link_to("Questions",faqs_index_path,:id=>"faqs")%></li>       <li><a href="http://www.kaluworks.com/about-us/the-company" target="blank" id="about">About Us</a></li>	
          </ul>
        </div><!--close menubar-->	
      </nav>		
	
	</header>
    
	<div id="site_content">		

      <div class="slideshow">
	    <ul class="slideshow">
              <li class="show"><%=image_tag("circles.jpg",:size=>"680x300",:alt=>"&quot;Quality aluminium products&quot;")%></li>
              <li><%=image_tag("Plates.jpg",:size=>"680x300",:alt=>"&quot;Quality aluminium products&quot;")%></li>
        </ul> 
	  </div><!--close slideshow-->	
	
	  <div class="sidebar_container">       			
        <div class="sidebar">
          <div class="sidebar_item">
 <%if user_signed_in?%>
          
                              <h1>Account Menu</h1>
                              <span>Logged in as:</span></br>
                              <%=current_user.email%>
                              <p> <span><%=link_to('Account update', edit_user_registration_path) %></span></p>
                              <span class="badge" id="logoutbtn"><%=link_to('Logout', destroy_user_session_path, :method => :delete,:id=>"logoutbtn") %></span>                    
                         <%else%> 
                              <h1>Portal Menu</h1>
                             			
                                      <a href="index.html">Home</a><br/>
                                      <a href="#faqs">Questions</a></br>
                                      <a href="#about">About Us</a></br>
			<%-end-%>	
 </div>		
          <div class="Sidebar_item">
            <h2>Important links</h2>
		  <a href="http://www.kaluworks.com" target="blank">Company website</a>
          </div>
          <div class="sidebar_item">
            <h2>Contact</h2>
            <p>Phone: +44 (0)1234 567891</p>
            <p>Email: <a href="mailto:juma.d.o@kaluworks.com">juma.d.o@kaluworks.com</a></p>
          </div><!--close sidebar_item--> 
        </div><!--close sidebar-->
       </div><!--close sidebar_container-->
	  <div id="content">
            <%if notice%>
                            <span  class="label label-success">
                              <a href="#"  data-dismiss="alert">&times;</a>
                            <%=notice %>
                          </span> 
                 <%-end-%>
            <p>
               <%= breadcrumbs pretext: "You are here: ",separator: " &rsaquo; " ,:class=>"breadcrumb"%>
            </p>
        		<%=yield%>  	  
		</div><!--close content_item-->
      </div><!--close content-->   
	
	</div><!--close site_content-->  	
  
    <footer>
	 &copy; 2014 Kaluworks Limited &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp; <a href="index.html">Home</a> |&nbsp; <a href="contact.html">Contact</a> &nbsp;|<br/>
    </footer> 
  
  </div><!--close main-->
</body>
</html>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<% breadcrumb :orders, orders_path %>
<% breadcrumb :root, root_path %>

     <%if alert%>
     <span class="label label-warning">
        <a href="#"  data-dismiss="alert">&times;</a>
         <%=alert %>
       <%flash[:alert]=nil%>
      </span> 
    <%-end-%>
    <%if notice%>
    <span class="label label-success">
      <a href="#"  data-dismiss="alert">&times;</a>
      <%=notice %>
    </span>
     <%flash[:notice]=nil%>
   <%-end-%>
<div class="page-header">
  <h1>Listing Orders</h1>
</div>
<%if @orders && @orders.count>0 %>
<div class="searchinfo">
  <%=search_form_for (@search),:class=>"navbar-form navbar-search",:role=> "search" do |f|%>
  <div class="form-group">
    <%=f.text_field :pono_cont,:placeholder=>"Search Purchase order number",:class=>"form-control input-large"%>
    <%=f.submit "Search",:class=>"btn btn-default"%>
  </div>
  <%-end-%>
</div>
<table class="table table-striped" id="orders">
  <thead>
    <tr>
      <th>PO NO.</th>
      <th>ORD. DATE</th>
      <th>LINKS</th>
    </tr>
  </thead>
  <tbody>
     
        <% @orders.each do |order| %>
          <tr>
            <td><%= order [:pono] %></td>
            <td><%= order[:orderdate]%></td>
            <td><span class="badge" id="backbtn"> <%=link_to 'Show',order_items_path(:order_id=>order[:order_id],:pono=>order[:pono]),:id=>"backbtn",:notice=>order[:pono],:email=>current_user.email%></span></td>
          </tr>
        <% end %>
</tbody>
</table>
<%if @orders.count>10%>
  <div class="well well-small">
  <ul class="pager">
    <li class="btn-mini"><%=will_paginate @orders,:container=>false%></li>
   </ul>
</div>
<%-end-%>
 <%else%>
           <span class="label label-success">
               <a href="#"  data-dismiss="alert">&times;</a>
                You have <%= @orders.count%> orders
            </span>       
 <%-end-%>
 

app/views/user/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_path, :class => 'btn' %>
  </div>
<% end %>

app/views/user/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/user/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>